set_property SRC_FILE_INFO {cfile:{/home/tranq/Desktop/ASIC Test/ip_pci_v1/ip_pci_v1.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc} rfile:../../../ip_pci_v1.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc id:1 order:EARLY} [current_design]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N14 [get_ports {c0_ddr3_dq[0]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N13 [get_ports {c0_ddr3_dq[1]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports {c0_ddr3_dq[2]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {c0_ddr3_dq[3]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M12 [get_ports {c0_ddr3_dq[4]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports {c0_ddr3_dq[5]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M11 [get_ports {c0_ddr3_dq[6]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L12 [get_ports {c0_ddr3_dq[7]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K14 [get_ports {c0_ddr3_dq[8]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K13 [get_ports {c0_ddr3_dq[9]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H13 [get_ports {c0_ddr3_dq[10]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J13 [get_ports {c0_ddr3_dq[11]}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports {c0_ddr3_dq[12]}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports {c0_ddr3_dq[13]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14 [get_ports {c0_ddr3_dq[14]}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {c0_ddr3_dq[15]}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15 [get_ports {c0_ddr3_dq[16]}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports {c0_ddr3_dq[17]}]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports {c0_ddr3_dq[18]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E14 [get_ports {c0_ddr3_dq[19]}]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13 [get_ports {c0_ddr3_dq[20]}]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G12 [get_ports {c0_ddr3_dq[21]}]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F14 [get_ports {c0_ddr3_dq[22]}]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {c0_ddr3_dq[23]}]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B14 [get_ports {c0_ddr3_dq[24]}]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C13 [get_ports {c0_ddr3_dq[25]}]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16 [get_ports {c0_ddr3_dq[26]}]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D15 [get_ports {c0_ddr3_dq[27]}]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D13 [get_ports {c0_ddr3_dq[28]}]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12 [get_ports {c0_ddr3_dq[29]}]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C16 [get_ports {c0_ddr3_dq[30]}]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D16 [get_ports {c0_ddr3_dq[31]}]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A24 [get_ports {c0_ddr3_dq[32]}]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B23 [get_ports {c0_ddr3_dq[33]}]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B27 [get_ports {c0_ddr3_dq[34]}]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B26 [get_ports {c0_ddr3_dq[35]}]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A22 [get_ports {c0_ddr3_dq[36]}]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B22 [get_ports {c0_ddr3_dq[37]}]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A25 [get_ports {c0_ddr3_dq[38]}]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C24 [get_ports {c0_ddr3_dq[39]}]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E24 [get_ports {c0_ddr3_dq[40]}]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D23 [get_ports {c0_ddr3_dq[41]}]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D26 [get_ports {c0_ddr3_dq[42]}]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C25 [get_ports {c0_ddr3_dq[43]}]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E23 [get_ports {c0_ddr3_dq[44]}]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D22 [get_ports {c0_ddr3_dq[45]}]
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports {c0_ddr3_dq[46]}]
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E22 [get_ports {c0_ddr3_dq[47]}]
set_property src_info {type:XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A30 [get_ports {c0_ddr3_dq[48]}]
set_property src_info {type:XDC file:1 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D27 [get_ports {c0_ddr3_dq[49]}]
set_property src_info {type:XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A29 [get_ports {c0_ddr3_dq[50]}]
set_property src_info {type:XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C28 [get_ports {c0_ddr3_dq[51]}]
set_property src_info {type:XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D28 [get_ports {c0_ddr3_dq[52]}]
set_property src_info {type:XDC file:1 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B31 [get_ports {c0_ddr3_dq[53]}]
set_property src_info {type:XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A31 [get_ports {c0_ddr3_dq[54]}]
set_property src_info {type:XDC file:1 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A32 [get_ports {c0_ddr3_dq[55]}]
set_property src_info {type:XDC file:1 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E30 [get_ports {c0_ddr3_dq[56]}]
set_property src_info {type:XDC file:1 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F29 [get_ports {c0_ddr3_dq[57]}]
set_property src_info {type:XDC file:1 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F30 [get_ports {c0_ddr3_dq[58]}]
set_property src_info {type:XDC file:1 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F27 [get_ports {c0_ddr3_dq[59]}]
set_property src_info {type:XDC file:1 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C30 [get_ports {c0_ddr3_dq[60]}]
set_property src_info {type:XDC file:1 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E29 [get_ports {c0_ddr3_dq[61]}]
set_property src_info {type:XDC file:1 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F26 [get_ports {c0_ddr3_dq[62]}]
set_property src_info {type:XDC file:1 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D30 [get_ports {c0_ddr3_dq[63]}]
set_property src_info {type:XDC file:1 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports {c0_ddr3_addr[15]}]
set_property src_info {type:XDC file:1 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports {c0_ddr3_addr[14]}]
set_property src_info {type:XDC file:1 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A21 [get_ports {c0_ddr3_addr[13]}]
set_property src_info {type:XDC file:1 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15 [get_ports {c0_ddr3_addr[12]}]
set_property src_info {type:XDC file:1 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17 [get_ports {c0_ddr3_addr[11]}]
set_property src_info {type:XDC file:1 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B21 [get_ports {c0_ddr3_addr[10]}]
set_property src_info {type:XDC file:1 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C19 [get_ports {c0_ddr3_addr[9]}]
set_property src_info {type:XDC file:1 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D17 [get_ports {c0_ddr3_addr[8]}]
set_property src_info {type:XDC file:1 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C18 [get_ports {c0_ddr3_addr[7]}]
set_property src_info {type:XDC file:1 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D20 [get_ports {c0_ddr3_addr[6]}]
set_property src_info {type:XDC file:1 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A16 [get_ports {c0_ddr3_addr[5]}]
set_property src_info {type:XDC file:1 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A17 [get_ports {c0_ddr3_addr[4]}]
set_property src_info {type:XDC file:1 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A19 [get_ports {c0_ddr3_addr[3]}]
set_property src_info {type:XDC file:1 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C20 [get_ports {c0_ddr3_addr[2]}]
set_property src_info {type:XDC file:1 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports {c0_ddr3_addr[1]}]
set_property src_info {type:XDC file:1 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports {c0_ddr3_addr[0]}]
set_property src_info {type:XDC file:1 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports {c0_ddr3_ba[2]}]
set_property src_info {type:XDC file:1 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C21 [get_ports {c0_ddr3_ba[1]}]
set_property src_info {type:XDC file:1 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D21 [get_ports {c0_ddr3_ba[0]}]
set_property src_info {type:XDC file:1 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E20 [get_ports {c0_ddr3_ras_n}]
set_property src_info {type:XDC file:1 line:550 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports {c0_ddr3_cas_n}]
set_property src_info {type:XDC file:1 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports {c0_ddr3_we_n}]
set_property src_info {type:XDC file:1 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports {c0_ddr3_reset_n}]
set_property src_info {type:XDC file:1 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19 [get_ports {c0_ddr3_cke[0]}]
set_property src_info {type:XDC file:1 line:574 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H20 [get_ports {c0_ddr3_odt[0]}]
set_property src_info {type:XDC file:1 line:580 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17 [get_ports {c0_ddr3_cs_n[0]}]
set_property src_info {type:XDC file:1 line:586 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M13 [get_ports {c0_ddr3_dm[0]}]
set_property src_info {type:XDC file:1 line:592 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15 [get_ports {c0_ddr3_dm[1]}]
set_property src_info {type:XDC file:1 line:598 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F12 [get_ports {c0_ddr3_dm[2]}]
set_property src_info {type:XDC file:1 line:604 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports {c0_ddr3_dm[3]}]
set_property src_info {type:XDC file:1 line:610 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C23 [get_ports {c0_ddr3_dm[4]}]
set_property src_info {type:XDC file:1 line:616 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D25 [get_ports {c0_ddr3_dm[5]}]
set_property src_info {type:XDC file:1 line:622 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C31 [get_ports {c0_ddr3_dm[6]}]
set_property src_info {type:XDC file:1 line:628 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F31 [get_ports {c0_ddr3_dm[7]}]
set_property src_info {type:XDC file:1 line:633 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H19 [get_ports {c0_sys_clk_p}]
set_property src_info {type:XDC file:1 line:638 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18 [get_ports {c0_sys_clk_n}]
set_property src_info {type:XDC file:1 line:644 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N16 [get_ports {c0_ddr3_dqs_p[0]}]
set_property src_info {type:XDC file:1 line:650 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M16 [get_ports {c0_ddr3_dqs_n[0]}]
set_property src_info {type:XDC file:1 line:656 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K12 [get_ports {c0_ddr3_dqs_p[1]}]
set_property src_info {type:XDC file:1 line:662 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J12 [get_ports {c0_ddr3_dqs_n[1]}]
set_property src_info {type:XDC file:1 line:668 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports {c0_ddr3_dqs_p[2]}]
set_property src_info {type:XDC file:1 line:674 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16 [get_ports {c0_ddr3_dqs_n[2]}]
set_property src_info {type:XDC file:1 line:680 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C15 [get_ports {c0_ddr3_dqs_p[3]}]
set_property src_info {type:XDC file:1 line:686 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C14 [get_ports {c0_ddr3_dqs_n[3]}]
set_property src_info {type:XDC file:1 line:692 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A26 [get_ports {c0_ddr3_dqs_p[4]}]
set_property src_info {type:XDC file:1 line:698 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A27 [get_ports {c0_ddr3_dqs_n[4]}]
set_property src_info {type:XDC file:1 line:704 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F25 [get_ports {c0_ddr3_dqs_p[5]}]
set_property src_info {type:XDC file:1 line:710 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E25 [get_ports {c0_ddr3_dqs_n[5]}]
set_property src_info {type:XDC file:1 line:716 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B28 [get_ports {c0_ddr3_dqs_p[6]}]
set_property src_info {type:XDC file:1 line:722 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B29 [get_ports {c0_ddr3_dqs_n[6]}]
set_property src_info {type:XDC file:1 line:728 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E27 [get_ports {c0_ddr3_dqs_p[7]}]
set_property src_info {type:XDC file:1 line:734 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E28 [get_ports {c0_ddr3_dqs_n[7]}]
set_property src_info {type:XDC file:1 line:740 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports {c0_ddr3_ck_p[0]}]
set_property src_info {type:XDC file:1 line:746 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports {c0_ddr3_ck_n[0]}]
set_property src_info {type:XDC file:1 line:751 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y31 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:XDC file:1 line:752 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y30 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:XDC file:1 line:753 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y29 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:XDC file:1 line:754 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y28 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:XDC file:1 line:755 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y35 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:XDC file:1 line:756 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y34 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:XDC file:1 line:757 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y33 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:XDC file:1 line:758 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y39 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:XDC file:1 line:759 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y38 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:XDC file:1 line:760 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y37 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:XDC file:1 line:761 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y36 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:XDC file:1 line:764 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y31 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:765 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y30 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:766 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y29 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:767 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y28 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:771 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y39 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:772 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y38 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:773 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y37 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:774 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y36 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:780 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y31 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:XDC file:1 line:781 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y30 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:XDC file:1 line:782 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y29 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:XDC file:1 line:783 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y28 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:XDC file:1 line:784 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y35 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:XDC file:1 line:785 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y34 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:XDC file:1 line:786 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y33 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:XDC file:1 line:787 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y39 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:XDC file:1 line:788 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y38 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:XDC file:1 line:789 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y37 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:XDC file:1 line:790 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y36 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:XDC file:1 line:793 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y31 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:794 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y30 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:795 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y29 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:796 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y28 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:797 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y39 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:798 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y38 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:799 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y37 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:800 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y36 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:803 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y7 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:XDC file:1 line:804 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y8 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:XDC file:1 line:805 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y9 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:XDC file:1 line:808 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y7 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:XDC file:1 line:809 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y8 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:XDC file:1 line:810 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y9 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:XDC file:1 line:813 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y393 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:814 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y381 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:815 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y369 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:816 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y357 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:817 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y493 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:818 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y481 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:819 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y469 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:820 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y457 [get_cells  -hier -filter {NAME =~ */c0_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:824 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y8 [get_cells -hier -filter {NAME =~ */c0_u_ddr3_infrastructure/plle2_i}]
set_property src_info {type:XDC file:1 line:825 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y8 [get_cells -hier -filter {NAME =~ */c0_u_ddr3_infrastructure/gen_ui_extra_clocks.mmcm_i}]
set_property src_info {type:XDC file:1 line:833 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] -hold 5
set_property src_info {type:XDC file:1 line:840 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -hold 1 -start
set_property src_info {type:XDC file:1 line:844 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5
set_property src_info {type:XDC file:1 line:848 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr3_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20
set_property src_info {type:XDC file:1 line:877 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN24 [get_ports {c1_ddr3_dq[0]}]
set_property src_info {type:XDC file:1 line:883 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM24 [get_ports {c1_ddr3_dq[1]}]
set_property src_info {type:XDC file:1 line:889 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR22 [get_ports {c1_ddr3_dq[2]}]
set_property src_info {type:XDC file:1 line:895 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR23 [get_ports {c1_ddr3_dq[3]}]
set_property src_info {type:XDC file:1 line:901 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN23 [get_ports {c1_ddr3_dq[4]}]
set_property src_info {type:XDC file:1 line:907 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM23 [get_ports {c1_ddr3_dq[5]}]
set_property src_info {type:XDC file:1 line:913 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN21 [get_ports {c1_ddr3_dq[6]}]
set_property src_info {type:XDC file:1 line:919 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP21 [get_ports {c1_ddr3_dq[7]}]
set_property src_info {type:XDC file:1 line:925 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK23 [get_ports {c1_ddr3_dq[8]}]
set_property src_info {type:XDC file:1 line:931 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ23 [get_ports {c1_ddr3_dq[9]}]
set_property src_info {type:XDC file:1 line:937 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL21 [get_ports {c1_ddr3_dq[10]}]
set_property src_info {type:XDC file:1 line:943 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM21 [get_ports {c1_ddr3_dq[11]}]
set_property src_info {type:XDC file:1 line:949 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ21 [get_ports {c1_ddr3_dq[12]}]
set_property src_info {type:XDC file:1 line:955 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ20 [get_ports {c1_ddr3_dq[13]}]
set_property src_info {type:XDC file:1 line:961 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK20 [get_ports {c1_ddr3_dq[14]}]
set_property src_info {type:XDC file:1 line:967 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL20 [get_ports {c1_ddr3_dq[15]}]
set_property src_info {type:XDC file:1 line:973 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW22 [get_ports {c1_ddr3_dq[16]}]
set_property src_info {type:XDC file:1 line:979 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW23 [get_ports {c1_ddr3_dq[17]}]
set_property src_info {type:XDC file:1 line:985 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW21 [get_ports {c1_ddr3_dq[18]}]
set_property src_info {type:XDC file:1 line:991 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV21 [get_ports {c1_ddr3_dq[19]}]
set_property src_info {type:XDC file:1 line:997 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU23 [get_ports {c1_ddr3_dq[20]}]
set_property src_info {type:XDC file:1 line:1003 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV23 [get_ports {c1_ddr3_dq[21]}]
set_property src_info {type:XDC file:1 line:1009 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR24 [get_ports {c1_ddr3_dq[22]}]
set_property src_info {type:XDC file:1 line:1015 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT24 [get_ports {c1_ddr3_dq[23]}]
set_property src_info {type:XDC file:1 line:1021 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB24 [get_ports {c1_ddr3_dq[24]}]
set_property src_info {type:XDC file:1 line:1027 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA24 [get_ports {c1_ddr3_dq[25]}]
set_property src_info {type:XDC file:1 line:1033 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY23 [get_ports {c1_ddr3_dq[26]}]
set_property src_info {type:XDC file:1 line:1039 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY24 [get_ports {c1_ddr3_dq[27]}]
set_property src_info {type:XDC file:1 line:1045 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY25 [get_ports {c1_ddr3_dq[28]}]
set_property src_info {type:XDC file:1 line:1051 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA25 [get_ports {c1_ddr3_dq[29]}]
set_property src_info {type:XDC file:1 line:1057 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB21 [get_ports {c1_ddr3_dq[30]}]
set_property src_info {type:XDC file:1 line:1063 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA21 [get_ports {c1_ddr3_dq[31]}]
set_property src_info {type:XDC file:1 line:1069 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY14 [get_ports {c1_ddr3_dq[32]}]
set_property src_info {type:XDC file:1 line:1075 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW15 [get_ports {c1_ddr3_dq[33]}]
set_property src_info {type:XDC file:1 line:1081 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB14 [get_ports {c1_ddr3_dq[34]}]
set_property src_info {type:XDC file:1 line:1087 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB13 [get_ports {c1_ddr3_dq[35]}]
set_property src_info {type:XDC file:1 line:1093 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW12 [get_ports {c1_ddr3_dq[36]}]
set_property src_info {type:XDC file:1 line:1099 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY13 [get_ports {c1_ddr3_dq[37]}]
set_property src_info {type:XDC file:1 line:1105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY12 [get_ports {c1_ddr3_dq[38]}]
set_property src_info {type:XDC file:1 line:1111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA12 [get_ports {c1_ddr3_dq[39]}]
set_property src_info {type:XDC file:1 line:1117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU12 [get_ports {c1_ddr3_dq[40]}]
set_property src_info {type:XDC file:1 line:1123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU13 [get_ports {c1_ddr3_dq[41]}]
set_property src_info {type:XDC file:1 line:1129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT12 [get_ports {c1_ddr3_dq[42]}]
set_property src_info {type:XDC file:1 line:1135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU14 [get_ports {c1_ddr3_dq[43]}]
set_property src_info {type:XDC file:1 line:1141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV13 [get_ports {c1_ddr3_dq[44]}]
set_property src_info {type:XDC file:1 line:1147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW13 [get_ports {c1_ddr3_dq[45]}]
set_property src_info {type:XDC file:1 line:1153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT15 [get_ports {c1_ddr3_dq[46]}]
set_property src_info {type:XDC file:1 line:1159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR15 [get_ports {c1_ddr3_dq[47]}]
set_property src_info {type:XDC file:1 line:1165 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL15 [get_ports {c1_ddr3_dq[48]}]
set_property src_info {type:XDC file:1 line:1171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ15 [get_ports {c1_ddr3_dq[49]}]
set_property src_info {type:XDC file:1 line:1177 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK14 [get_ports {c1_ddr3_dq[50]}]
set_property src_info {type:XDC file:1 line:1183 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ12 [get_ports {c1_ddr3_dq[51]}]
set_property src_info {type:XDC file:1 line:1189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ16 [get_ports {c1_ddr3_dq[52]}]
set_property src_info {type:XDC file:1 line:1195 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL16 [get_ports {c1_ddr3_dq[53]}]
set_property src_info {type:XDC file:1 line:1201 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ13 [get_ports {c1_ddr3_dq[54]}]
set_property src_info {type:XDC file:1 line:1207 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK13 [get_ports {c1_ddr3_dq[55]}]
set_property src_info {type:XDC file:1 line:1213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR14 [get_ports {c1_ddr3_dq[56]}]
set_property src_info {type:XDC file:1 line:1219 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT14 [get_ports {c1_ddr3_dq[57]}]
set_property src_info {type:XDC file:1 line:1225 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM12 [get_ports {c1_ddr3_dq[58]}]
set_property src_info {type:XDC file:1 line:1231 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP11 [get_ports {c1_ddr3_dq[59]}]
set_property src_info {type:XDC file:1 line:1237 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM13 [get_ports {c1_ddr3_dq[60]}]
set_property src_info {type:XDC file:1 line:1243 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN13 [get_ports {c1_ddr3_dq[61]}]
set_property src_info {type:XDC file:1 line:1249 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM11 [get_ports {c1_ddr3_dq[62]}]
set_property src_info {type:XDC file:1 line:1255 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN11 [get_ports {c1_ddr3_dq[63]}]
set_property src_info {type:XDC file:1 line:1261 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL19 [get_ports {c1_ddr3_addr[15]}]
set_property src_info {type:XDC file:1 line:1267 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM19 [get_ports {c1_ddr3_addr[14]}]
set_property src_info {type:XDC file:1 line:1273 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK17 [get_ports {c1_ddr3_addr[13]}]
set_property src_info {type:XDC file:1 line:1279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL17 [get_ports {c1_ddr3_addr[12]}]
set_property src_info {type:XDC file:1 line:1285 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM18 [get_ports {c1_ddr3_addr[11]}]
set_property src_info {type:XDC file:1 line:1291 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM17 [get_ports {c1_ddr3_addr[10]}]
set_property src_info {type:XDC file:1 line:1297 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK19 [get_ports {c1_ddr3_addr[9]}]
set_property src_info {type:XDC file:1 line:1303 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK18 [get_ports {c1_ddr3_addr[8]}]
set_property src_info {type:XDC file:1 line:1309 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM16 [get_ports {c1_ddr3_addr[7]}]
set_property src_info {type:XDC file:1 line:1315 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN16 [get_ports {c1_ddr3_addr[6]}]
set_property src_info {type:XDC file:1 line:1321 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ18 [get_ports {c1_ddr3_addr[5]}]
set_property src_info {type:XDC file:1 line:1327 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP18 [get_ports {c1_ddr3_addr[4]}]
set_property src_info {type:XDC file:1 line:1333 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP17 [get_ports {c1_ddr3_addr[3]}]
set_property src_info {type:XDC file:1 line:1339 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP20 [get_ports {c1_ddr3_addr[2]}]
set_property src_info {type:XDC file:1 line:1345 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR19 [get_ports {c1_ddr3_addr[1]}]
set_property src_info {type:XDC file:1 line:1351 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN19 [get_ports {c1_ddr3_addr[0]}]
set_property src_info {type:XDC file:1 line:1357 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN18 [get_ports {c1_ddr3_ba[2]}]
set_property src_info {type:XDC file:1 line:1363 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR18 [get_ports {c1_ddr3_ba[1]}]
set_property src_info {type:XDC file:1 line:1369 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR17 [get_ports {c1_ddr3_ba[0]}]
set_property src_info {type:XDC file:1 line:1375 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV19 [get_ports {c1_ddr3_ras_n}]
set_property src_info {type:XDC file:1 line:1381 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT20 [get_ports {c1_ddr3_cas_n}]
set_property src_info {type:XDC file:1 line:1387 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU19 [get_ports {c1_ddr3_we_n}]
set_property src_info {type:XDC file:1 line:1393 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB19 [get_ports {c1_ddr3_reset_n}]
set_property src_info {type:XDC file:1 line:1399 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW17 [get_ports {c1_ddr3_cke[0]}]
set_property src_info {type:XDC file:1 line:1405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT16 [get_ports {c1_ddr3_odt[0]}]
set_property src_info {type:XDC file:1 line:1411 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV16 [get_ports {c1_ddr3_cs_n[0]}]
set_property src_info {type:XDC file:1 line:1417 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT22 [get_ports {c1_ddr3_dm[0]}]
set_property src_info {type:XDC file:1 line:1423 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL22 [get_ports {c1_ddr3_dm[1]}]
set_property src_info {type:XDC file:1 line:1429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU24 [get_ports {c1_ddr3_dm[2]}]
set_property src_info {type:XDC file:1 line:1435 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB23 [get_ports {c1_ddr3_dm[3]}]
set_property src_info {type:XDC file:1 line:1441 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB12 [get_ports {c1_ddr3_dm[4]}]
set_property src_info {type:XDC file:1 line:1447 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV15 [get_ports {c1_ddr3_dm[5]}]
set_property src_info {type:XDC file:1 line:1453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK12 [get_ports {c1_ddr3_dm[6]}]
set_property src_info {type:XDC file:1 line:1459 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP13 [get_ports {c1_ddr3_dm[7]}]
set_property src_info {type:XDC file:1 line:1464 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY18 [get_ports {c1_sys_clk_p}]
set_property src_info {type:XDC file:1 line:1469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY17 [get_ports {c1_sys_clk_n}]
set_property src_info {type:XDC file:1 line:1475 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP23 [get_ports {c1_ddr3_dqs_p[0]}]
set_property src_info {type:XDC file:1 line:1481 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP22 [get_ports {c1_ddr3_dqs_n[0]}]
set_property src_info {type:XDC file:1 line:1487 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ22 [get_ports {c1_ddr3_dqs_p[1]}]
set_property src_info {type:XDC file:1 line:1493 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK22 [get_ports {c1_ddr3_dqs_n[1]}]
set_property src_info {type:XDC file:1 line:1499 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT21 [get_ports {c1_ddr3_dqs_p[2]}]
set_property src_info {type:XDC file:1 line:1505 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU21 [get_ports {c1_ddr3_dqs_n[2]}]
set_property src_info {type:XDC file:1 line:1511 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA22 [get_ports {c1_ddr3_dqs_p[3]}]
set_property src_info {type:XDC file:1 line:1517 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB22 [get_ports {c1_ddr3_dqs_n[3]}]
set_property src_info {type:XDC file:1 line:1523 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA15 [get_ports {c1_ddr3_dqs_p[4]}]
set_property src_info {type:XDC file:1 line:1529 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA14 [get_ports {c1_ddr3_dqs_n[4]}]
set_property src_info {type:XDC file:1 line:1535 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP12 [get_ports {c1_ddr3_dqs_p[5]}]
set_property src_info {type:XDC file:1 line:1541 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR12 [get_ports {c1_ddr3_dqs_n[5]}]
set_property src_info {type:XDC file:1 line:1547 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK15 [get_ports {c1_ddr3_dqs_p[6]}]
set_property src_info {type:XDC file:1 line:1553 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL14 [get_ports {c1_ddr3_dqs_n[6]}]
set_property src_info {type:XDC file:1 line:1559 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN15 [get_ports {c1_ddr3_dqs_p[7]}]
set_property src_info {type:XDC file:1 line:1565 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN14 [get_ports {c1_ddr3_dqs_n[7]}]
set_property src_info {type:XDC file:1 line:1571 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT17 [get_ports {c1_ddr3_ck_p[0]}]
set_property src_info {type:XDC file:1 line:1577 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU17 [get_ports {c1_ddr3_ck_n[0]}]
set_property src_info {type:XDC file:1 line:1582 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:XDC file:1 line:1583 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:XDC file:1 line:1584 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:XDC file:1 line:1585 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:XDC file:1 line:1586 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y11 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:XDC file:1 line:1587 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y10 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:XDC file:1 line:1588 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y9 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:XDC file:1 line:1589 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y15 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property src_info {type:XDC file:1 line:1590 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y14 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]
set_property src_info {type:XDC file:1 line:1591 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y13 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_out}]
set_property src_info {type:XDC file:1 line:1592 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_OUT_PHY_X1Y12 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property src_info {type:XDC file:1 line:1595 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y7 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:1596 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y6 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:1597 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y5 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:1598 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y4 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:1602 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y15 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:1603 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y14 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:1604 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y13 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:1605 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_IN_PHY_X1Y12 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property src_info {type:XDC file:1 line:1611 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:XDC file:1 line:1612 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:XDC file:1 line:1613 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:XDC file:1 line:1614 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:XDC file:1 line:1615 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y11 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:XDC file:1 line:1616 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y10 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:XDC file:1 line:1617 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y9 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:XDC file:1 line:1618 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y15 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property src_info {type:XDC file:1 line:1619 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y14 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]
set_property src_info {type:XDC file:1 line:1620 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y13 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/out_fifo}]
set_property src_info {type:XDC file:1 line:1621 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OUT_FIFO_X1Y12 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property src_info {type:XDC file:1 line:1624 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y7 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:1625 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y6 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:1626 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y5 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:1627 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y4 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:1628 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y15 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:1629 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y14 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:1630 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y13 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:1631 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IN_FIFO_X1Y12 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/in_fifo_gen.in_fifo}]
set_property src_info {type:XDC file:1 line:1634 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y1 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:XDC file:1 line:1635 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y2 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:XDC file:1 line:1636 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHY_CONTROL_X1Y3 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]
set_property src_info {type:XDC file:1 line:1639 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y1 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:XDC file:1 line:1640 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y2 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_1.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:XDC file:1 line:1641 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PHASER_REF_X1Y3 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]
set_property src_info {type:XDC file:1 line:1644 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y93 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:1645 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y81 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:1646 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y69 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:1647 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y57 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_2.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:1648 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y193 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:1649 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y181 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:1650 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y169 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_B.ddr_byte_lane_B/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:1651 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC OLOGIC_X1Y157 [get_cells  -hier -filter {NAME =~ */c1_u_memc_ui_top_axi/*/ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/ddr_byte_group_io/*slave_ts}]
set_property src_info {type:XDC file:1 line:1655 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PLLE2_ADV_X1Y2 [get_cells -hier -filter {NAME =~ */c1_u_ddr3_infrastructure/plle2_i}]
set_property src_info {type:XDC file:1 line:1656 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X1Y2 [get_cells -hier -filter {NAME =~ */c1_u_ddr3_infrastructure/gen_mmcm.mmcm_i}]
